import './globals.css'

import type { Metadata } from 'next'
import {
  Inter,
  Island_Moments as IslandMoments,
  Londrina_Solid as LondrinaSolid,
} from 'next/font/google'

import { Footer } from '@/components/footer'
import { Header } from '@/components/header'

const inter = Inter({
  subsets: ['latin'],
  style: 'normal',
  weight: ['200', '300', '400', '700', '900'],
  variable: '--font-inter',
})
const londrinaSolid = LondrinaSolid({
  subsets: ['latin'],
  style: 'normal',
  weight: ['400'],
  variable: '--font-londrinaSolid',
})
const islandMoments = IslandMoments({
  subsets: ['latin'],
  style: 'normal',
  weight: ['400'],
  variable: '--font-islandMoments',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="pt-Br">
      <body
        className={`${inter.variable} ${londrinaSolid.variable} ${islandMoments.variable} bg-background-color text-typography`}
      >
        <Header />
        <div className="relative w-full min-w-72 max-w-7xl pl-8 font-sans md:mx-auto md:px-8">
          {children}
        </div>
        <Footer />
      </body>
    </html>
  )
}
